# List of unique wine names extracted from dataset.csv

WINE_NAMES = [
    '1792 Aged Twelve Years',
    '1792 Bottled In Bond',
    '1792 Full Proof',
    '1792 Single Barrel',
    '1792 Small Batch',
    '1792 Sweet Wheat Bourbon',
    '2XO American Oak Oak Series Kentucky Straight Bourbon',
    'Alberta Premium Cask Strength',
    'Ancient Age',
    'Angel\'s Envy',
    'Angel\'s Envy Cask Strength',
    'Angel\'s Envy Rye',
    'Angel\'s Envy Rye Caribbean Rum Cask',
    'Angel’s Envy Triple Oak',
    'Baker\'s 13 Year Single Barrel',
    'Baker\'s 7 Year 107 Proof',
    'Balvenie 14 Year Caribbean Cask',
    'Bardstown Discovery Series No. 11',
    'Bardstown Discovery Series No. 5',
    'Bardstown Fusion Series No. 5',
    'Bardstown Origin Series Bottled in Bond',
    'Bardstown Origin Series Bourbon',
    'Bardstown Origin Series Wheated Bourbon',
    'Barrell Bourbon Infinite Barrel Project',
    'Barrell Bourbon Single Barrel',
    'Barrell Dovetail',
    'Barrell Seagrass Rye Whiskey',
    'Barrell Vantage',
    'Basil Hayden Subtle Smoke',
    'Basil Hayden Toast',
    'Basil Hayden\'s 10 Year',
    'Basil Hayden\'s 10 Year Bourbon',
    'Basil Hayden\'s Bourbon',
    'Basil Hayden\'s Dark Rye',
    'Belle Meade Bourbon',
    'Belle Meade Cask Strength Reserve Bourbon',
    'Ben Holladay Bottled in Bond Bourbon',
    'Ben Holladay Soft Red Wheat Bottled in Bond',
    'Ben Holladay Soft Red Wheat Rickhouse Proof',
    'Benchmark Bonded',
    'Benchmark Full Proof',
    'Benchmark No. 8',
    'Benchmark Select Casks Small Batch',
    'Benchmark Single Barrel',
    'Benchmark Top Floor',
    'Bernheim Original Kentucky Straight Wheat Whiskey',
    'Bib & Tucker 6 Year Small Batch Bourbon',
    'Blackened',
    'Blade and Bow Bourbon',
    'Blanton\'s',
    'Blanton\'s Black',
    'Blanton\'s Gold Edition',
    'Blanton\'s Original Single Barrel',
    'Blanton\'s Red',
    'Blanton\'s Special Reserve',
    'Blanton\'s Straight from the Barrel',
    'Blood Oath Pact No. 10',
    'Blood Oath Pact No. 7',
    'Blood Oath Pact No. 8',
    'Blood Oath Pact No.9',
    'Blue Note Bourbon',
    'Blue Note Crossroads',
    'Blue Note Juke Joint Whiskey Uncut Unfiltered',
    'Blue Run 13 Year Old',
    'Blue Run High Rye Bourbon',
    'Blue Spot 7 Year Batch 3',
    'Bomberger Small Batch Straight Bourbon',
    'Bomberger’s Declaration 2024 Release',
    'Booker\'s 6 Year "Tagalong Batch" - 2021',
    'Booker\'s 7 Year "Apprentice Batch" - 2023',
    'Booker\'s 7 Year "The Beam House Batch" - 2024',
    'Booker\'s Bourbon',
    'Booker\'s Bourbon 2022-01 Ronnie’s Batch',
    'Booker\'s Bourbon 2022-03 Kentucky Tea Batch',
    'Booker\'s Bourbon 2023-03 Mighty Fine Batch',
    'Booker’s  Springfield Batch 2024-01',
    'Booker’s 2023-01 Charlie’s Batch',
    'Booker’s Bourbon 2021-03 Bardstown Batch',
    'Booker’s Bourbon 2021-04 Noe Strangers Batch',
    'Booker’s Bourbon 2022-02 Lumberyard Batch',
    'Booker’s Bourbon 2023-04 - The Storyteller Batch',
    'Booker’s Bourbon 2024-03',
    'Bowman Brothers Small Batch',
    'Breckenridge Bourbon Whiskey',
    'Brother\'s Bond Bourbon',
    'Buffalo Trace',
    'Buffalo Trace Bourbon Cream',
    'Buffalo Trace Kosher Bourbon Rye Recipe',
    'Buffalo Trace Kosher Rye 7 Year',
    'Buffalo Trace Kosher Wheat 7 Year',
    'Buffalo Trace White Dog Mash 1',
    'Bulleit 12 Year Rye',
    'Bulleit 95 Rye',
    'Bulleit Bourbon',
    'Bulleit Bourbon 10 Year',
    'Bulleit Bourbon Barrel Strength',
    'Calumet Farm 14 Year',
    'Calumet Farm 15 Year Single Rack Black',
    'Calumet Farm 16 year Single Rack Black',
    'Caribou Crossing',
    'Castle & Key Restoration Rye',
    'Castle & Key Small Batch Bourbon',
    'Chattanooga Whiskey Experimental Single Barrel 75',
    'Chicken Cock Straight Bourbon',
    'Clase Azul Reposado',
    'Colonel E.H. Taylor Amaranth',
    'Colonel E.H. Taylor Barrel Proof - Batch 6',
    'Colonel E.H. Taylor Barrel Proof Batch 12',
    'Colonel E.H. Taylor Warehouse C',
    'Coopers\' Craft Barrel Reserve',
    'Crown Royal',
    'Crown Royal Blackberry',
    'Crown Royal Peach',
    'Crown Royal Regal Apple',
    'Crown Royal Salted Caramel',
    'Crown Royal XR Extra Rare 18 Year',
    'Don Julio 1942',
    'Double Eagle Very Rare',
    'E.H. Taylor, Jr. 18 Year Marriage',
    'E.H. Taylor, Jr. Single Barrel',
    'E.H. Taylor, Jr. Small Batch',
    'E.H. Taylor, Jr. Straight Rye',
    'Eagle Rare',
    'Eagle Rare 10 Year',
    'Eagle Rare 17 Year',
    'Early Times Bottled In Bond',
    'Elijah Craig 18 Year Single Barrel',
    'Elijah Craig 1991 20 Year Single Barrel #42',
    'Elijah Craig 23 Year Single Barrel',
    'Elijah Craig Barrel Proof - Batch B524',
    'Elijah Craig Barrel Proof A124',
    'Elijah Craig Barrel Proof Batch A119',
    'Elijah Craig Barrel Proof Batch A121',
    'Elijah Craig Barrel Proof Batch A122',
    'Elijah Craig Barrel Proof Batch B519',
    'Elijah Craig Barrel Proof Batch B521',
    'Elijah Craig Barrel Proof Batch B522',
    'Elijah Craig Barrel Proof Batch B523',
    'Elijah Craig Barrel Proof Batch C917',
    'Elijah Craig Barrel Proof Batch C921',
    'Elijah Craig Barrel Proof Batch C922',
    'Elijah Craig Barrel Proof C923',
    'Elijah Craig Barrel Proof C924',
    'Elijah Craig Small Batch',
    'Elijah Craig Straight Rye Whiskey',
    'Elijah Craig Toasted Barrel',
    'Elmer T Lee Commemorative Edition',
    'Elmer T. Lee',
    'Elmer T. Lee Sour Mash',
    'Evan Williams 12 Year Red Label',
    'Evan Williams Black Label',
    'Evan Williams Bottled in Bond Green Label',
    'Evan Williams Bottled in Bond White Label',
    'Evan Williams Single Barrel Vintage 1988',
    'Evan Williams Single Barrel Vintage 2012',
    'Evan Williams Single Barrel Vintage 2013',
    'Evan Williams Single Barrel Vintage 2014',
    'Evan Williams Single Barrel Vintage 2015',
    'Ezra Brooks Cask Strength',
    'Ezra Brooks Distiller\'s Collection',
    'Fortaleza Blanco Tequila',
    'Fortaleza Reposado Tequila',
    'Four Roses 2020 Limited Edition Small Batch OESV',
    'Four Roses Bourbon',
    'Four Roses Single Barrel',
    'Four Roses Single Barrel Barrel Proof OESV',
    'Four Roses Single Barrel Straight Bourbon',
    'Four Roses Small Batch',
    'Four Roses Small Batch Select',
    'Frank August Small Batch Bourbon',
    'Frey Ranch Bourbon',
    'Garrison Brothers Balmorhea Bourbon',
    'Gentleman Jack',
    'George Dickel 15 Year Single Barrel',
    'George Dickel Bottled in Bond Tennessee Whiskey 13 Year',
    'George Dickel x Leopold Brothers Collaboration',
    'George Remus Single Barrel',
    'George Remus Straight Bourbon Whiskey',
    'George T Stagg - 2024',
    'George T. Stagg 2009 Release',
    'George T. Stagg 2022 Release',
    'George T. Stagg 2023 Release',
    'Glenfiddich Single Malt Scotch Whiskey 12 Years',
    'Glenlivet 12 Year',
    'Green River Bourbon DSP-KY-10',
    'Green River Full Proof',
    'Green River Wheated Sour Mash',
    'Green Spot',
    'Hancock\'s President\'s Reserve Bourbon',
    'Heaven Hill 17 Year Heritage Collection 2022 Release',
    'Heaven Hill Bottled In Bond 7 Year',
    'Heaven Hill Grain to Glass Kentucky Straight Bourbon Whiskey',
    'Heaven Hill Grain to Glass-Rye',
    'Heaven Hill Old Style Bourbon 6 Year',
    'Heaven Hill: Grain to Glass - Wheated Bourbon',
    'Heaven’s Door Decade Series 10 Year Release 1',
    'Hendrick\'s Gin',
    'Henry McKenna 10 Year',
    'Hibiki Harmony',
    'Hibiki Japanese Harmony',
    'High West A Midwinter Night\'s Dram Act 4 Scene 5',
    'High West American Prairie Bourbon',
    'High West Bourye',
    'High West Campfire',
    'High West Double Rye',
    'High West Midwinter Nights Dram Act 10 Scene 1: The Encore',
    'High West Rendezvous Rye',
    'Horse Soldier Barrel Strength',
    'Horse Soldier Bourbon',
    'Horse Soldier Small Batch',
    'I.W. Harper 15 Year',
    'Isaac Bowman Port Barrel Finish Bourbon',
    'J.T.S. Brown BIB Bourbon',
    'Jack Daniel\'s',
    'Jack Daniel\'s 10 Year',
    'Jack Daniel\'s Bonded',
    'Jack Daniel\'s Bottled in Bond',
    'Jack Daniel\'s Coy Hill Barrelhouse 8 2024 Special Release Single Barrel Whiskey',
    'Jack Daniel\'s Coy Hill Single Barrel',
    'Jack Daniel\'s No. 27 Gold Maple Wood Finish',
    'Jack Daniel\'s Sinatra Select',
    'Jack Daniel\'s Single Barrel Barrel Proof',
    'Jack Daniel\'s Single Barrel Eric Church',
    'Jack Daniel\'s Single Barrel Rye',
    'Jack Daniel\'s Single Barrel Rye Barrel Proof',
    'Jack Daniel\'s Single Barrel Select',
    'Jack Daniel’s 12 Year Tennessee Whiskey #1',
    'Jack Daniel’s Triple Mash',
    'Jack Daniel’s Twice Barreled Special Release 2022 American Single Malt Finished in Oloroso Sherry Casks',
    'Jack Daniel’s Twice Barreled Tennessee Rye 2023 Special Release',
    'James E. Pepper Barrel Proof Bourbon',
    'Jameson Black Barrel',
    'Jameson Irish Whiskey Triple Distilled',
    'Jefferson\'s Kentucky Straight Bourbon Whiskey Very Small Batch',
    'Jefferson\'s Ocean Aged At Sea Voyage 17',
    'Jefferson\'s Reserve Twin Oak Barrel',
    'Jefferson’s Reserve Very Old Kentucky Straight Bourbon Very Small Batch',
    'Jim Beam Black 7 Year',
    'Jim Beam Double Oak',
    'John J. Bowman Single Barrel 10 Year',
    'John J. Bowman Single Barrel Limited Edition',
    'Johnnie Walker Black Label',
    'Johnnie Walker Blue Label',
    'Johnny Drum Private Stock 15 Year',
    'Joseph Magnus Cigar Blend Bourbon',
    'Joseph Magnus Straight Bourbon',
    'Kentucky Owl Confiscated',
    'Kentucky Owl St. Patrick\'s Edition',
    'Kentucky Owl Takumi Edition',
    'King Of Kentucky',
    'Kirkland Signature Bottled-in-Bond Bourbon Barton 1792',
    'Kirkland Signature Small Batch',
    'Knob Creek 12 Year',
    'Knob Creek 12 Year Cask Strength',
    'Knob Creek 15 Year Batch KC001',
    'Knob Creek 18 Year Limited Edition',
    'Knob Creek 9 Year',
    'Knob Creek 9 Year Single Barrel Reserve',
    'Knob Creek Rye',
    'Knob Creek Single Barrel Rye',
    'Knob Creek Smoked Maple',
    'Lagavulin 16 Year',
    'Laphroaig 10 Year',
    'Larceny',
    'Larceny Barrel Proof',
    'Larceny Barrel Proof - Batch B524',
    'Larceny Barrel Proof A123',
    'Larceny Barrel Proof A124',
    'Larceny Barrel Proof Batch A122',
    'Larceny Barrel Proof Batch B522',
    'Larceny Barrel Proof Batch B523',
    'Larceny Barrel Proof Batch C921',
    'Larceny Barrel Proof Batch C923',
    'Larceny Barrel Proof C924',
    'Larceny Small Batch',
    'Legent Bourbon Whiskey',
    'Little Book Chapter 5: The Invitation',
    'Little Book Chapter 6: To The Finish',
    'Little Book Chapter 7: In Retrospect',
    'Little Book Chapter 8: Path Not Taken',
    'Little Book The Infinite I 2024',
    'Lux Row Four Grain Double Single Barrel',
    'Lux Row Limited Edition Whiskey 12 Year',
    'Macallan 12 Year Double Cask',
    'Maker\'s Mark 101',
    'Maker\'s Mark 2021 Wood Finishing Series FAE-01',
    'Maker\'s Mark 2021 Wood Finishing Series FAE-02',
    'Maker\'s Mark 2023 Wood Finishing Series BEP',
    'Maker\'s Mark 46',
    'Maker\'s Mark 46 Cask Strength',
    'Maker\'s Mark Bourbon',
    'Maker\'s Mark Cask Strength',
    'Maker\'s Mark Cellar Aged 2023 Release',
    'Maker\'s Mark Cellar Aged 2024 Release',
    'Maker\'s Mark Wood Finish Series The Heart Release 2024',
    'Maker’s Mark 2022 Wood Finishing Series BRT-01',
    'Maker’s Mark 2022 Wood Finishing Series BRT-02',
    'Maker’s Mark French Oaked No. 46 Cask Strength 23-01',
    'Mellow Corn Bottled In Bond',
    'Michter\'s 10 Year Single Barrel Bourbon 2020 Bottling',
    'Michter\'s Barrel Strength Rye Whiskey',
    'Michter\'s Limited Release Toasted Barrel Bourbon',
    'Michter\'s Limited Release Toasted Barrel Strength',
    'Michter\'s Single Barrel Rye 10 Year',
    'Michter\'s Toasted Barrel Strength Rye Whiskey',
    'Michter\'s US1 Kentucky Straight Bourbon',
    'Michter\'s US1 Kentucky Straight Rye',
    'Michter\'s US1 Toasted Sour Mash',
    'Michter\'s US1 Unblended American Whiskey',
    'Monkey Shoulder',
    'Murray Hill Club Bourbon',
    'New Riff 6 Year Malted Rye',
    'New Riff Bourbon',
    'New Riff Bourbon Single Barrel',
    'New Riff Bourbon Single Barrel Barrel Proof',
    'Nikka Coffey Grain Japanese Whisky',
    'Nikka Whisky From The Barrel',
    'Noah\'s Mill',
    'Noble Oak Double Oak Bourbon',
    'Old Bardstown Bottled in Bond',
    'Old Elk Blended Straight Bourbon',
    'Old Elk Cigar Cut',
    'Old Elk Wheated Bourbon',
    'Old Ezra 7 Year Barrel Strength',
    'Old Fitzgerald 10 Year',
    'Old Fitzgerald 13 Year',
    'Old Fitzgerald 14 Year - Fall 2020',
    'Old Fitzgerald 15 Year',
    'Old Fitzgerald 16 Year',
    'Old Fitzgerald 17 Year',
    'Old Fitzgerald 19 Year - Fall 2022',
    'Old Fitzgerald 8 Year - Fall 2023',
    'Old Fitzgerald 8 Year - Spring 2021',
    'Old Forester 100',
    'Old Forester 150th Anniversary',
    'Old Forester 1870 Original Batch',
    'Old Forester 1897 Bottled In Bond',
    'Old Forester 1910 Old Fine Whiskey',
    'Old Forester 1920 Prohibition Style',
    'Old Forester 1924 10 Year',
    'Old Forester 86 Proof',
    'Old Forester Birthday Bourbon 2022',
    'Old Forester Birthday Bourbon 2024',
    'Old Forester Rye',
    'Old Forester Rye Barrel Strength Single Barrel',
    'Old Forester Single Barrel 100 Proof',
    'Old Forester Statesman',
    'Old Grand Dad',
    'Old Grand Dad 114',
    'Old Grand Dad Bonded',
    'Old Rip Van Winkle 10 Year',
    'Old Tub',
    'Orphan Barrel Fabel and Folly',
    'Pappy Van Winkle 15 Year Family Reserve',
    'Pappy Van Winkle 20 Year Family Reserve',
    'Pappy Van Winkle 23 Year Family Reserve',
    'Peerless Bourbon Small Batch',
    'Peerless Double Oak Bourbon',
    'Peerless Double Oak Rye',
    'Penelope 5 Year Toasted Barrel',
    'Penelope Architect',
    'Penelope Barrel Strength Private Select - 4 Grain - 9 Yr',
    'Penelope Bourbon Barrel Strength Four Grain Batch 8',
    'Penelope Bourbon Cooper Series - Valencia',
    'Penelope Bourbon Four Grain',
    'Penelope Bourbon Rosé Cask Finish',
    'Penelope Double Cask Finish - Rio',
    'Penelope Estate Collection Private Select 9 Year',
    'Penelope Rio Batch 2',
    'Penelope Toasted Series',
    'Pikesville Rye Whiskey',
    'RD One Bourbon Brazilian Amburana Wood Finish',
    'Rabbit Hole Cavehill',
    'Rabbit Hole Dareringer Sherry Bourbon Cask',
    'Rabbit Hole Heigold',
    'Rebel 10 Year Single Barrel',
    'Rebel Cask Strength Single Barrel',
    'Redbreast 12 Year Cask Strength',
    'Redbreast 12 Year Old Single Pot Still',
    'Redwood Empire Emerald Giant',
    'Redwood Empire Emerald Giant Cask Strength',
    'Redwood Empire Grizzly Beast Straight Bourbon Bottled in Bond',
    'Redwood Empire Lost Monarch',
    'Redwood Empire Lost Monarch Cask Strength',
    'Redwood Empire Pipe Dream',
    'Redwood Empire Pipe Dream Cask Strength',
    'Redwood Empire Rocket Top BIB Rye',
    'Redwood Empire Screaming Titan',
    'Remus Repeal Reserve V',
    'Remus Repeal Reserve VI',
    'Rittenhouse Rye',
    'Rock Hill Farms Bourbon',
    'Rowan\'s Creek 12 Year',
    'Russell\'s Reserve 10 Year',
    'Russell\'s Reserve 13 Years Bourbon',
    'Russell\'s Reserve 6 Years Rye',
    'Russell\'s Reserve Bourbon Single Rickhouse',
    'Russell\'s Reserve Single Barrel Rye',
    'Russell’s Reserve 15 Year',
    'Russell’s Reserve Private Barrel Selection Single Barrel',
    'Russell’s Reserve Single Barrel',
    'Sagamore Spirit Rye Double Oak',
    'Sam Houston Bourbon 15 Year',
    'Sazerac Rye 18 Year',
    'Sazerac Rye Whiskey',
    'Shenk\'s Homestead Sour Mash Whiskey 2022 Release',
    'Shenks Homstead Sour Mash Whiskey - 2024 Release',
    'Shenk’s Homestead Sour Mash Whiskey 2023 Release',
    'Skrewball Peanut Butter Whiskey',
    'Smoke Wagon Bourbon',
    'Smoke Wagon Small Batch Bourbon',
    'Smoke Wagon Straight Bourbon Halloween Edition',
    'Smoke Wagon Uncut Unfiltered Bourbon',
    'Smoke Wagon Uncut the Younger',
    'Stagg - 22A',
    'Stagg - 23A',
    'Stagg - 23C',
    'Stagg - Batch #18',
    'Stagg 127.8 Proof',
    'Stagg 24B',
    'Stagg 24C',
    'Stagg Batch 22B',
    'Stagg Batch 24A',
    'Stagg Jr.',
    'Stagg Jr. - Batch #16',
    'Stagg Jr. - Batch #17',
    'Stagg Jr. Batch 15',
    'Still Austin Bourbon The Musician',
    'Still Austin Cask Strength Bourbon',
    'Suntory Toki Japanese Whiskey',
    'The Balvenie Double Wood 12 year',
    'Thirteenth Colony Distilleries Southern Bourbon Whiskey',
    'Thomas H Handy',
    'Tincup American Whiskey 10 Year',
    'Tito\'s Handmade Vodka',
    'Traveller Whiskey',
    'Uncle Nearest 1856',
    'Uncle Nearest 1884 Small Batch',
    'Van Winkle 12 Year Special Reserve Lot "B"',
    'Van Winkle Family Reserve 13 Year Rye',
    'Very Old Barton 6 Year 100 Proof',
    'W.B. Saffell',
    'Weller 12 Year 1 Liter',
    'Weller 12 Year The Original Wheated Bourbon',
    'Weller Antique 107',
    'Weller C.Y.P.B.',
    'Weller Full Proof',
    'Weller Single Barrel',
    'Weller Special Reserve',
    'WhistlePig 10 Year Single Barrel',
    'WhistlePig 10 Year Straight Rye',
    'WhistlePig 12 Year Old World',
    'WhistlePig 6 Year Piggyback Bourbon',
    'WhistlePig 6 Year Piggyback Rye',
    'Widow Jane 10 Year Straight Bourbon',
    'Widow Jane Decadence',
    'Widow Jane Lucky Thirteen',
    'Widow Jane The Vaults 15 Year',
    'Wild Turkey 101',
    'Wild Turkey 101 Rye',
    'Wild Turkey 12 Year',
    'Wild Turkey Jimmy Russell 70th Anniversary',
    'Wild Turkey Kentucky Spirit Single Barrel',
    'Wild Turkey Longbranch 8 Year',
    'Wild Turkey Master\'s Keep One',
    'Wild Turkey Rare Breed',
    'Wild Turkey Rare Breed Barrel Proof Rye',
    'Wilderness Trail Small Batch Bourbon',
    'Willett Family Estate Small Batch Rye 4 Year',
    'Willett Pot Still Reserve Bourbon',
    'Willett Wheated 8 Year',
    'William Larue Weller - 2009',
    'Woodford Reserve Bourbon',
    'Woodford Reserve Derby 150 2024 Release',
    'Woodford Reserve Double Oaked',
    'Woodford Reserve Five-Malt Stouted Mash - 2021',
    'Woodford Reserve Master\'s Collection Batch Proof 121.2',
    'Woodford Reserve Master\'s Collection Batch Proof 128.3',
    'Woodford Reserve Master’s Collection Batch Proof 124.7',
    'Woodford Reserve Rye',
    'Woodford Reserve Wheat',
    'Woodinville Straight Bourbon',
    'Yamazaki 12 Year',
    'Yellowstone Limited Edition 2021',
    'Yellowstone Select',
    'Yellowstone Select Landmark Edition',
]
